"""update character table

Revision ID: 08c7e998f232
Revises: b6a0de4760da
Create Date: 2025-05-12 15:38:18.949498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c7e998f232'
down_revision: Union[str, None] = 'b6a0de4760da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('aliases', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('characters', sa.Column('backstory', sa.Text(), nullable=False))
    op.add_column('characters', sa.Column('motivations', sa.Text(), nullable=False))
    op.add_column('characters', sa.Column('catchphrases', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('sample_dialogues', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('knowledge_domains', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('characters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('characters', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('characters', 'bio')
    op.drop_column('characters', 'quotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('quotes', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('characters', 'updated_at')
    op.drop_column('characters', 'created_at')
    op.drop_column('characters', 'avatar_url')
    op.drop_column('characters', 'knowledge_domains')
    op.drop_column('characters', 'sample_dialogues')
    op.drop_column('characters', 'catchphrases')
    op.drop_column('characters', 'motivations')
    op.drop_column('characters', 'backstory')
    op.drop_column('characters', 'description')
    op.drop_column('characters', 'aliases')
    # ### end Alembic commands ###
