"""add google_id to profiles

Revision ID: dea77c7b8c86
Revises: 63a3b48e560e
Create Date: 2025-07-07 21:35:04.223547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea77c7b8c86'
down_revision: Union[str, None] = '63a3b48e560e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('google_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_profiles_google_id'), 'profiles', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_google_id'), table_name='profiles')
    op.drop_column('profiles', 'google_id')
    # ### end Alembic commands ###
